title: "Deep Learning Reproducibility Paper Project"
author: "M. Constantinov (5007445, M.Constantinov@student.tudelft.nl), C. Pabsch (5064015, C.M.N.Pabsch@student.tudelft.nl), I. Pszczolkowski (5091934, I.A.Pszczolkowski@student.tudelft.nl)"
description: "EfficientNetV2 paper reproducibility project, part of the CS4220 Deep Learning course at TU Delft, 2023." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
# email: "example@mail.com"
# twitter_username: "twitteruser"
# github_username: "githubuser"
# linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
